config/routes.rb
Rails.application.routes.draw do
  get 'coaches/schedule'

  get 'coaches/book'

  post 'coaches/timeslot'

  root 'coaches#book'

end

app/models/availability.rb
class Availability < ActiveRecord::Base
  belongs_to :coach, dependent: :destroy
  has_many :timeslots
end

app/models/coach.rb
class Coach < ActiveRecord::Base
  has_many :availabilities
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  belongs_to :availability, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  def schedule
  end

  def timeslot
    #change the booked timeslot to true
    @timeslot = Timeslot.find_by_id(timeslot_params[:id])
    @timeslot.booked = true
    @timeslot.save
    @coach = Coach.find_by_name(timeslot_params[:coach_name])
  end

  def book
    #fetch all the coaches for display
    @coaches = Coach.all
  end

  private

  def timeslot_params
    params.require(:timeslot).permit(:id, :coach_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
  def generateTimeslots(availability)
    #Uses a start and end time interval to generate a list of 30min timeslots.
    #add 30mins to availability.available_from,add to array.
    #fetch last time and add 30mins as long as last timeslot.to time is 30mins less than availability.available_to
    timeslots = []

    if timeslots.empty?
      timeslots << Timeslot.create!(from: availability.available_from, to: availability.available_from + 30.minutes, day_of_week: availability.day_of_week, booked: false)
      puts "---=-=-=-=-=-=-=created timeslot -=-=-=-=-==-=-=-=-" + timeslots.to_s
    end

    puts "=--=timeslots.last-=-=-=" + timeslots.to_s
    while (availability.available_to - timeslots.last.to) >= 30.minutes
      timeslots << Timeslot.create!(from: timeslots.last.to, to: timeslots.last.to + 30.minutes, day_of_week: availability.day_of_week, booked: false)
    end
    return timeslots
  end
end

app/views/coaches/book.html.erb
<h1>Book a Coach</h1>
<table style="width:100%">
  <tr style="text-align: justify">
    <th>Name</th>
    <th>Timezone</th>
    <th>Day of Week</th>
    <th>Available From</th>
    <th>Available Until</th>
  </tr>
  <%@coaches.each do |coach|%>
    <tr>
      <td><%= coach.name %></td>
      <%coach.availabilities.each do |availability|%>
        <%availability.timeslots.each do |timeslot|%>
          <%if timeslot.booked == false%>
            <tr>
              <td> - </td>
              <td><%= availability.timezone %></td>
              <td><%= timeslot.day_of_week %></td>
              <td><%= timeslot.from.strftime("%r") %></td>
              <td>
                <%= timeslot.to.strftime("%r") %>
                <%= link_to 'Book', coaches_timeslot_path(timeslot: {id: timeslot.id, coach_name: coach.name}).to_param, method: :post %>
              </td>
            </tr>
          <%end%>
        <%end%>
      <%end%>
    </tr>
  <%end%>
</table>

app/views/coaches/schedule.html.erb
<h1>Coaches#schedule</h1>
<p>Find me in app/views/coaches/schedule.html.erb</p>

app/views/coaches/timeslot.html.erb
<h1>You successfully made a booking</h1>
<div>
  <%="You have booked coach #{@coach.name} from #{@timeslot.day_of_week} #{@timeslot.from.strftime("%r")} to #{@timeslot.day_of_week} #{@timeslot.to.strftime("%r")} #{@coach.availabilities.first.timezone}"%>
</div>

<p>
  <%=link_to "Make another Booking", coaches_book_path%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetterupScheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>